MinimumStatiqWebVersion-CleanBlog: "1.0.0-beta.36"

# Hosting settings
Host: jcoo092.github.io # Host name - This example is for GitHub pages
LinksUseHttps: true # Whether to generate HTTPS links in archives etc. - usually true, of course

SiteTitle: James Cooper, PhD
SiteDescription: A small site acting as a blog host and online CV
PageTitle: |
  =>
  {
    string siteTitle = Context.GetString("SiteTitle");
    string title = GetString("Title");
    return string.IsNullOrWhiteSpace(siteTitle) ? title : (string.IsNullOrWhiteSpace(title) ? siteTitle : $"{siteTitle} - {title}");
  }
Copyright: => $"Copyright © James Cooper {DateTime.Now.Year}.  To the maximum extent possible, permission is explicitly denied for using the content of this site to train machine learning models."
PostSources: posts/**/*
IsPost: => Context.Outputs.FilterSources(Context.GetString("PostSources")).ContainsById(Document)
PageSources: pages/**/*
IsPage: => Context.Outputs.FilterSources(Context.GetString("PageSources")).ContainsById(Document)
Layout: /_layout.cshtml
# Blog settings
DateTimeInputCulture: "dd-MM-yyyy" # This determines the expected format for Published dates in posts - Empty string means invariant culture (yyyy-MM-dd format)
DateTimeDisplayCulture: en-NZ # This determines the format for displayed dates, e.g. in post headers and archive pages
GenerateSearchIndex: true # Setting this to false disables both the search box in navigation bar and the search page