name: Deploy Site
on: [push]

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7' # SDK Version to use.
      - run: dotnet run -c Release -- deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
